version: 2
updates:
  - package-ecosystem: npm
    directory: "/musicteam-nuxt"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directories:
      - "/"
      - "/musicteam"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
