name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'kgutwin/musicteam'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Update pre-commit versions
        run: |
          python -m pip install -r requirements-dev.txt -r musicteam/requirements.txt
          python musicteam/pre_commit_requirements_sync.py --in-place
          git config --local user.email "karl@gutwin.org"
          git config --local user.name "Karl Gutwin"
          git diff
          git add .pre-commit-config.yaml
          git commit -m "chore(deps): sync pre-commit config"
          git push

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
